export const products = [
  {
    id: 1,
    name: 'Paper Towel Holder',
    category: 'Home Decor',
    base_price: 549,
    rating: 4.8,
    reviews: 126,
    image_url: '/images/p1.png',
    description: 'A modern, 3D-printed paper towel holder that looks great in any kitchen. Sturdy, easy to load and built to last.',
    options: JSON.stringify(['Single', 'Set of 2']),
    featured: 0,
    customizable: 0,
    estimated_days: 3,
  },
  {
    id: 2,
    name: 'Sunglass Organiser',
    category: 'Home Decor',
    base_price: 449,
    rating: 4.6,
    reviews: 203,
    image_url: '/images/p2.png',
    description: 'A neat, 3D-printed organiser that keeps your sunglasses safe, scratch-free and easy to grab.',
    options: JSON.stringify(['Small', 'Medium', 'Large']),
    featured: 0,
    customizable: 0,
    estimated_days: 3,
  },
  {
    id: 3,
    name: 'Outlet Box',
    category: 'Home Decor',
    base_price: 799,
    rating: 4.9,
    reviews: 88,
    image_url: '/images/p3.png',
    description: 'A practical, 3D-printed outlet box that tidies cables and adds extra storage beside your power points. Neatly organised and easy to install.',
    options: JSON.stringify(['Single', 'Double']),
    featured: 0,
    customizable: 0,
    estimated_days: 4,
  },
  {
    id: 4,
    name: 'Desk Accessories',
    category: 'Office',
    base_price: 899,
    rating: 4.7,
    reviews: 152,
    image_url: '/images/p4.png',
    description: 'Stylish, printed desk accessories that keep your workspace tidy. From pen pots to cable clips, built to be both practical and good-looking.',
    options: JSON.stringify(['Starter', 'Complete', 'Deluxe']),
    featured: 0,
    customizable: 0,
    estimated_days: 5,
  },
  {
    id: 5,
    name: 'Headphones & Watch Holder',
    category: 'Home Decor',
    base_price: 349,
    rating: 4.5,
    reviews: 319,
    image_url: '/images/p5.png',
    description: 'A compact, 3D-printed holder that stores your headphones and watch together in one tidy spot. Keeps them off the desk and always within reach.',
    options: JSON.stringify(['Black', 'White', 'Green']),
    featured: 0,
    customizable: 0,
    estimated_days: 3,
  },
  {
    id: 6,
    name: 'Eco-Friendly Plant Pot',
    category: 'Garden',
    base_price: 299,
    rating: 4.4,
    reviews: 241,
    image_url: '/images/p6.png',
    description: 'A sustainable, 3D-printed plant pot made from eco-friendly materials. Stylish, durable and perfect for your favourite plants.',
    options: JSON.stringify(['Small', 'Medium', 'Large']),
    featured: 0,
    customizable: 0,
    estimated_days: 2,
  },
  {
    id: 7,
    name: 'Animal Fidget & Keyring',
    category: 'Toys',
    base_price: 179,
    rating: 4.8,
    reviews: 126,
    image_url: '/images/best1.png',
    description: 'A fun, 3D-printed animal fidget and keyring in one. Satisfying to play with and handy to clip onto your keys or bag.',
    options: JSON.stringify(['Rabbit', 'Cat', 'Bear']),
    featured: 1,
    customizable: 0,
    estimated_days: 2,
  },
  {
    id: 8,
    name: 'Jewellery Holder',
    category: 'Home Decor',
    base_price: 449,
    rating: 4.6,
    reviews: 203,
    image_url: '/images/best2.png',
    description: 'A stylish, 3D-printed jewellery holder that keeps your rings, earrings and necklaces organised, tangle-free and easy to grab.',
    options: JSON.stringify(['Small', 'Medium', 'Large']),
    featured: 1,
    customizable: 0,
    estimated_days: 3,
  },
  {
    id: 9,
    name: 'Game Controller Stand',
    category: 'Gaming',
    base_price: 549,
    rating: 4.9,
    reviews: 88,
    image_url: '/images/best3.png',
    description: 'A sturdy, 3D-printed stand that holds your game controller neatly when you are done playing. Keeps your setup tidy and your controller safe.',
    options: JSON.stringify(['Single', 'Double']),
    featured: 1,
    customizable: 0,
    estimated_days: 3,
  },
  {
    id: 10,
    name: 'Sweet Dispenser',
    category: 'Toys',
    base_price: 199,
    rating: 4.6,
    reviews: 98,
    image_url: '/images/p7.png',
    description: 'A fun, 3D-printed sweet dispenser that makes it easy to hand out your favourite treats. Perfect for parties, kids and playful kitchens.',
    options: JSON.stringify(['Small', 'Large']),
    featured: 0,
    customizable: 0,
    estimated_days: 2,
  },
]

export const users = [
  {
    id: 1,
    email: 'admin@reprint.com',
    name: 'Admin User',
    password: 'password123',
    role: 'admin',
  },
  {
    id: 2,
    email: 'user@reprint.com',
    name: 'Regular User',
    password: 'user123',
    role: 'user',
  },
]

export const employees = [
  { id: 1, employee_id: 'EMP001', name: 'Sipho Mbali', position: 'Print Technician', department: 'Production', employment_type: 'Full-time', hire_date: '2023-03-15', salary: 28000, status: 'active' },
  { id: 2, employee_id: 'EMP002', name: 'Aisha Khan', position: 'Designer', department: 'Design', employment_type: 'Full-time', hire_date: '2023-06-01', salary: 32000, status: 'active' },
  { id: 3, employee_id: 'EMP003', name: 'Thabo Nkosi', position: 'Warehouse Manager', department: 'Logistics', employment_type: 'Full-time', hire_date: '2022-11-20', salary: 35000, status: 'active' },
  { id: 4, employee_id: 'EMP004', name: 'Zanele Dlamini', position: 'Customer Support', department: 'Support', employment_type: 'Part-time', hire_date: '2024-01-10', salary: 15000, status: 'active' },
  { id: 5, employee_id: 'EMP005', name: 'Liam van der Merwe', position: '3D Printing Specialist', department: 'Production', employment_type: 'Full-time', hire_date: '2023-09-05', salary: 30000, status: 'active' },
  { id: 6, employee_id: 'EMP006', name: 'Naledi Mokoena', position: 'Marketing Lead', department: 'Marketing', employment_type: 'Full-time', hire_date: '2022-08-12', salary: 38000, status: 'active' },
  { id: 7, employee_id: 'EMP007', name: 'Johan Pretorius', position: 'Quality Inspector', department: 'Production', employment_type: 'Contract', hire_date: '2024-04-01', salary: 22000, status: 'on_leave' },
  { id: 8, employee_id: 'EMP008', name: 'Fatima Patel', position: 'HR Coordinator', department: 'HR', employment_type: 'Full-time', hire_date: '2023-01-20', salary: 34000, status: 'active' },
  { id: 9, employee_id: 'EMP009', name: 'David Mthembu', position: 'Shipping Clerk', department: 'Logistics', employment_type: 'Part-time', hire_date: '2024-06-15', salary: 14000, status: 'inactive' },
  { id: 10, employee_id: 'EMP010', name: 'Chloe Smith', position: 'Graphic Designer', department: 'Design', employment_type: 'Full-time', hire_date: '2024-02-28', salary: 29000, status: 'active' },
]

export const shifts = [
  { id: 1, employee_id: 1, employee_name: 'Sipho Mbali', position: 'Print Technician', shift_date: new Date().toISOString().slice(0, 10), start_time: '07:00', end_time: '15:00', break_minutes: 30, status: 'scheduled' },
  { id: 2, employee_id: 2, employee_name: 'Aisha Khan', position: 'Designer', shift_date: new Date().toISOString().slice(0, 10), start_time: '08:00', end_time: '16:00', break_minutes: 45, status: 'scheduled' },
  { id: 3, employee_id: 3, employee_name: 'Thabo Nkosi', position: 'Warehouse Manager', shift_date: new Date().toISOString().slice(0, 10), start_time: '06:00', end_time: '14:00', break_minutes: 30, status: 'in_progress' },
  { id: 4, employee_id: 5, employee_name: 'Liam van der Merwe', position: '3D Printing Specialist', shift_date: new Date().toISOString().slice(0, 10), start_time: '07:00', end_time: '15:00', break_minutes: 30, status: 'scheduled' },
  { id: 5, employee_id: 6, employee_name: 'Naledi Mokoena', position: 'Marketing Lead', shift_date: new Date().toISOString().slice(0, 10), start_time: '09:00', end_time: '17:00', break_minutes: 60, status: 'scheduled' },
  { id: 6, employee_id: 8, employee_name: 'Fatima Patel', position: 'HR Coordinator', shift_date: new Date().toISOString().slice(0, 10), start_time: '08:30', end_time: '16:30', break_minutes: 45, status: 'scheduled' },
  { id: 7, employee_id: 4, employee_name: 'Zanele Dlamini', position: 'Customer Support', shift_date: new Date().toISOString().slice(0, 10), start_time: '09:00', end_time: '13:00', break_minutes: 15, status: 'completed' },
  { id: 8, employee_id: 10, employee_name: 'Chloe Smith', position: 'Graphic Designer', shift_date: new Date().toISOString().slice(0, 10), start_time: '08:00', end_time: '16:00', break_minutes: 45, status: 'scheduled' },
]
